### ISSUE TITLE
Setup Walkthrough

### ISSUE THREAD

**Issue by Modulations** [davidayoub/IT490Project#14]
Ended up breaking my VM (twice) and decided to throw this guide together in case any of you guys do the same.

# PHP Setup
`sudo apt install software-properties-common`
`sudo add-apt-repository ppa:ondrej/php`
`sudo apt update`
`sudo apt install php8.0 php8.0-cli php8.0-fpm php8.0-common php8.0-mysql php8.0-zip php8.0-gd php8.0-mbstring php8.0-curl php8.0-xml php8.0-bcmath libapache2-mod-php8.0`
`sudo service apache2 restart`

# MySQL & PHPMyAdmin Setup
`sudo apt-get install software-properties-common -y`
`sudo add-apt-repository ppa:phpmyadmin/ppa`
`sudo apt update`
`sudo apt install phpmyadmin`
`sudo a2enmod ssl`
`sudo a2ensite default-ssl`
`sudo service apache2 restart`
`cd /usr/share/phpmyadmin/`
`sudo cp config.sample.inc.php config.inc.php`

# Database Setup
`sudo apt install mysql-server`
`cat /etc/mysql/debian.cnf`
`sudo mysql`
`mysql> ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';`
`mysql> FLUSH PRIVILEGES;`
`mysql> exit`
`mysql -u root -p`
(input password)

# Testing
`cd ~/Desktop/IT490Project`
`php -S localhost:8080`
(change the port if you want)
go to the web address:
http://127.0.0.1:8080/rabbitmq/rabbitmqphp_example/mysqlconnect.php

IF YOU SEE `#!/usr/bin/php successfully connected to database` it works
IF YOU SEE `#!/usr/bin/php` and nothing else, look in the console to see your error and resolve it accordingly

# PHPMyAdmin Access
Go to the web address:
https://localhost/phpmyadmin/
Username: root
Password: password (or the password you used earlier with ALTER USER)

If it fails, ask me or resolve accordingly

**Comment by alejjuuu** [comment]
Thank you Luke!

**Comment by alejjuuu** [comment]
Not used.
