### ISSUE TITLE
Database Authentication login and register page

### ISSUE THREAD

**Issue by davidayoub** [davidayoub/IT490Project#8]
Create Database for Authentication login and register page. Users will be able to register for an account and be able to login with their credentials. Data should be saved in database.

**Comment by alejjuuu** [comment]
I've have modified the login/register login page to be a single one.

**Comment by alejjuuu** [comment]
I have change boostrap for tailwing and daisyUI.

**Comment by alejjuuu** [comment]
Php back-end side works, but when trying to connect to the database it fails due that the database hasn't yet been create with the database form and root user root and password 12345.

**Comment by Modulations** [comment]
See commit [8fb4f29](https://github.com/davidayoub/IT490Project/commit/8fb4f29e6e06d701ce944df6047b4ba502c48489), user's data will be saved to the database if it exists locally.
